---
- hosts: panos
  connection: local
  gather_facts: False
  environment:
    PYTHONHTTPSVERIFY: 0
  tasks:
    - name: CHECK iF READY
      panos_check:
        username: "{{ panos_username }} "
        password: "{{ panos_password }}"
        ip_address: "{{ ansible_ssh_host }}"
